---
- hosts: all
  gather_facts: no
  connection: local
  
  tasks:
  - name: show running config
    ios_command:
      commands: show running-config
    register: Print_output
  
  - debug: msg="{{ Print_output.stdout}}"
  - name: save output to a file
      copy: content="{{'\n########\n show running-config\n********\n\n' + print_output.stdout|join('\n\n============================================\n\n')}}" 
