---
- hosts: all
  gather_facts: no
  connection: local
  
  tasks:
  - name: show running config
    ios_command:
      commands: show running-config
    register: print_output
   -  debug: var=print_output.stdout_lines
   - name: Append block
      lineinfile:
        dest: ./prechecks_XE/{{ inventory_hostname }}.txt
        line: "{{'\n########\n show run\n********\n\n' + print_output.stdout|join('\n\n============================================\n\n')}}"
        insertafter: EOF
